apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: pkg-cue.test.carvel.dev.2.0.0
spec:
  refName: pkg-cue.test.carvel.dev
  version: 2.0.0
  template: # type of App CR
    spec:
      fetch:
      - imgpkgBundle:
          image: index.docker.io/k14stest/test-cue@sha256:28a294453369ec83b592736803c790a5a4f9f495b28143ab98f8c4ac8cf35670
      template:
      - cue:
          paths:
          - github.com/uhthomas/automata/k8s/pillowtalk/cert_manager
          outputExpression: "list"
      - kbld:
          paths:
          - "-"
          - .imgpkg/images.yml
      deploy:
      - kapp: {}
