apiVersion: v1
kind: Namespace
metadata:
  name: dev
---
apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: simple-app
  namespace: dev
spec:
  serviceAccountName: dev-ns-sa
  fetch:
  - git:
      url: https://github.com/k14s/gitopscon-cue
      ref: origin/main
      subPath: ex1b-k8s-api
  template:
  - cue:
      paths:
      - ./dev
      outputExpression: "all"
  deploy:
  - kapp: {}
